=begin
#Reseplaneraren

#Provides access to Västtrafik journey planner

OpenAPI spec version: 1.10.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.28

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::GeometryApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GeometryApi' do
  before do
    # run before each test
    @instance = SwaggerClient::GeometryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GeometryApi' do
    it 'should create an instance of GeometryApi' do
      expect(@instance).to be_instance_of(SwaggerClient::GeometryApi)
    end
  end

  # unit tests for get_geometry
  # Returns the polyline for a leg.
  # Returns the polyline for a leg. This service can not be called directly but only by reference URLs in a result of a trip or JourneyDetail request. The result contains a list of WGS84 coordinates which can be used to display the polyline on a map.If the parameter needItinerary&#x3D;1 is passed in the URL of the trip request that contained the reference to the Geometry service, the geometry reference link will also contain an itinerary for walk, bike and car legs, that can be used to generate turn-by-turn instructions.
  # @param ref the ref query parameter, URL decoded, from a URL retrieved as a result of a trip or JourneyDetail request
  # @param [Hash] opts the optional parameters
  # @return [Geometry]
  describe 'get_geometry test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
