=begin
#Reseplaneraren

#Provides access to Västtrafik journey planner

OpenAPI spec version: 1.10.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.28

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::LivemapApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LivemapApi' do
  before do
    # run before each test
    @instance = SwaggerClient::LivemapApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LivemapApi' do
    it 'should create an instance of LivemapApi' do
      expect(@instance).to be_instance_of(SwaggerClient::LivemapApi)
    end
  end

  # unit tests for livemap
  # Returns the positions of all vehicles in a given bounding box
  # This method will return the positions of all vehicles in a given bounding box.
  # @param minx Left border (longitude) of the bounding box in WGS84 * 1000000
  # @param maxx Right border (longitude) of the bounding box in WGS84 * 1000000
  # @param miny Lower border (latitude) of the bounding box in WGS84 * 1000000
  # @param maxy Upper border (latitude) of the bounding box in WGS84 * 1000000
  # @param only_realtime Can be used to define whether all vehicles should be returned or only those  vehicles which have realtime information. If it is set to yes, only vehicles  with realtime information are returned, if it is set to no, all vehicles in the  bounding box are returned.
  # @param [Hash] opts the optional parameters
  # @return [LiveMap]
  describe 'livemap test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
