=begin
#Reseplaneraren

#Provides access to Västtrafik journey planner

OpenAPI spec version: 1.10.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.28

=end

require 'date'

module SwaggerClient
  class Leg
    # Foregroundcolor of this line
    attr_accessor :fg_color

    # Will be true if this journey needs to be booked
    attr_accessor :booking

    # Direction information
    attr_accessor :direction

    attr_accessor :journey_detail_ref

    # Will be true if this journey is cancelled
    attr_accessor :cancelled

    # Energy use
    attr_accessor :kcal

    attr_accessor :origin

    # Short name of the leg
    attr_accessor :sname

    # The attribute type specifies the type of the leg. Valid values are VAS, LDT (Long Distance Train), REG (Regional train), BUS , BOAT, TRAM, TAXI (Taxi/Telebus). Furthermore it can be of type WALK, BIKE and CAR if these legs are routes on the street network
    attr_accessor :type

    attr_accessor :geometry_ref

    # Backgroundcolor of this line
    attr_accessor :bg_color

    attr_accessor :notes

    # ID of the journey
    attr_accessor :id

    # Stroke style of this line
    attr_accessor :stroke

    # Will be true if this journey is not reachable due to delay of the feeder
    attr_accessor :reachable

    # The attribute name specifies the name of the leg
    attr_accessor :name

    # Will be true if this journey is a night journey
    attr_accessor :night

    attr_accessor :destination

    # Percentage of the route that is made up of bike roads
    attr_accessor :percent_bike_road

    # will only be set if the vehicle has wheelchair + ramp/lift or lowfloor according to realtime data
    attr_accessor :accessibility

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'fg_color' => :'fgColor',
        :'booking' => :'booking',
        :'direction' => :'direction',
        :'journey_detail_ref' => :'JourneyDetailRef',
        :'cancelled' => :'cancelled',
        :'kcal' => :'kcal',
        :'origin' => :'Origin',
        :'sname' => :'sname',
        :'type' => :'type',
        :'geometry_ref' => :'GeometryRef',
        :'bg_color' => :'bgColor',
        :'notes' => :'Notes',
        :'id' => :'id',
        :'stroke' => :'stroke',
        :'reachable' => :'reachable',
        :'name' => :'name',
        :'night' => :'night',
        :'destination' => :'Destination',
        :'percent_bike_road' => :'percentBikeRoad',
        :'accessibility' => :'accessibility'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'fg_color' => :'String',
        :'booking' => :'BOOLEAN',
        :'direction' => :'String',
        :'journey_detail_ref' => :'JourneyDetailRef',
        :'cancelled' => :'BOOLEAN',
        :'kcal' => :'Float',
        :'origin' => :'Origin',
        :'sname' => :'String',
        :'type' => :'String',
        :'geometry_ref' => :'GeometryRef',
        :'bg_color' => :'String',
        :'notes' => :'Notes',
        :'id' => :'String',
        :'stroke' => :'String',
        :'reachable' => :'BOOLEAN',
        :'name' => :'String',
        :'night' => :'BOOLEAN',
        :'destination' => :'Destination',
        :'percent_bike_road' => :'Float',
        :'accessibility' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'fgColor')
        self.fg_color = attributes[:'fgColor']
      end

      if attributes.has_key?(:'booking')
        self.booking = attributes[:'booking']
      end

      if attributes.has_key?(:'direction')
        self.direction = attributes[:'direction']
      end

      if attributes.has_key?(:'JourneyDetailRef')
        self.journey_detail_ref = attributes[:'JourneyDetailRef']
      end

      if attributes.has_key?(:'cancelled')
        self.cancelled = attributes[:'cancelled']
      end

      if attributes.has_key?(:'kcal')
        self.kcal = attributes[:'kcal']
      end

      if attributes.has_key?(:'Origin')
        self.origin = attributes[:'Origin']
      end

      if attributes.has_key?(:'sname')
        self.sname = attributes[:'sname']
      end

      if attributes.has_key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.has_key?(:'GeometryRef')
        self.geometry_ref = attributes[:'GeometryRef']
      end

      if attributes.has_key?(:'bgColor')
        self.bg_color = attributes[:'bgColor']
      end

      if attributes.has_key?(:'Notes')
        self.notes = attributes[:'Notes']
      end

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'stroke')
        self.stroke = attributes[:'stroke']
      end

      if attributes.has_key?(:'reachable')
        self.reachable = attributes[:'reachable']
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'night')
        self.night = attributes[:'night']
      end

      if attributes.has_key?(:'Destination')
        self.destination = attributes[:'Destination']
      end

      if attributes.has_key?(:'percentBikeRoad')
        self.percent_bike_road = attributes[:'percentBikeRoad']
      end

      if attributes.has_key?(:'accessibility')
        self.accessibility = attributes[:'accessibility']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @type.nil?
      return false if @name.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          fg_color == o.fg_color &&
          booking == o.booking &&
          direction == o.direction &&
          journey_detail_ref == o.journey_detail_ref &&
          cancelled == o.cancelled &&
          kcal == o.kcal &&
          origin == o.origin &&
          sname == o.sname &&
          type == o.type &&
          geometry_ref == o.geometry_ref &&
          bg_color == o.bg_color &&
          notes == o.notes &&
          id == o.id &&
          stroke == o.stroke &&
          reachable == o.reachable &&
          name == o.name &&
          night == o.night &&
          destination == o.destination &&
          percent_bike_road == o.percent_bike_road &&
          accessibility == o.accessibility
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [fg_color, booking, direction, journey_detail_ref, cancelled, kcal, origin, sname, type, geometry_ref, bg_color, notes, id, stroke, reachable, name, night, destination, percent_bike_road, accessibility].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
