=begin
#Reseplaneraren

#Provides access to Västtrafik journey planner

OpenAPI spec version: 1.10.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.28

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ArrivalBoardApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ArrivalBoardApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ArrivalBoardApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ArrivalBoardApi' do
    it 'should create an instance of ArrivalBoardApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ArrivalBoardApi)
    end
  end

  # unit tests for get_arrival_board
  # Return the next 20 arrivals (or less if not existing) from a given point in time or the next arrivals in a given timespan.
  # This method will return the next 20 arrivals (or less if not existing) from a given point in time or the next arrivals in a given timespan. The service can only be called for stops/stations by using according ID retrieved by the location method. The parameter is called id. The time and date are defined with the parameters date and time.
  # @param id stop id
  # @param date the date
  # @param time the time in format HH:MM
  # @param direction stop id in order to get only departures of vehicles with a specified direction
  # @param [Hash] opts the optional parameters
  # @option opts [String] :use_vas to exclude trips with Västtågen, set this parameter to 0.
  # @option opts [String] :use_ld_train to exclude trips with long distance trains, set this parameter to 0.
  # @option opts [String] :use_reg_train to exclude trips with regional trains, set this parameter to 0.
  # @option opts [String] :use_bus to exclude trips with buses, set this parameter to 0.
  # @option opts [String] :use_boat to exclude trips with boats, set this parameter to 0.
  # @option opts [String] :use_tram to exclude trips with trams, set this parameter to 0.
  # @option opts [String] :exclude_dr to exclude journeys which require tel. registration, set this parameter to 0.
  # @option opts [Integer] :time_span to get the next departures in a specified timespan of up to 24 hours (unit: minutes). If this parameter is not set, the result will contain the next 20 departures.
  # @option opts [Integer] :max_departures_per_line if timeSpan is set you can further reduce the number of returned journeys by adding this parameter, which will cause only the given number of journeys for every combination of line and direction.
  # @option opts [String] :need_journey_detail if the reference URL for the journey detail service is not needed in the result, set this parameter to 0
  # @option opts [String] :format the required response format
  # @option opts [String] :jsonp_callback If JSONP response format is needed, you can append an additional parameter to specify the name of a callback function, and the JSON object will be wrapped by a function call with this name.
  # @return [ArrivalBoard]
  describe 'get_arrival_board test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
