=begin
#Reseplaneraren

#Provides access to Västtrafik journey planner

OpenAPI spec version: 1.10.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.28

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::JourneyDetailApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'JourneyDetailApi' do
  before do
    # run before each test
    @instance = SwaggerClient::JourneyDetailApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JourneyDetailApi' do
    it 'should create an instance of JourneyDetailApi' do
      expect(@instance).to be_instance_of(SwaggerClient::JourneyDetailApi)
    end
  end

  # unit tests for get_journey_detail
  # Returns information about the complete route of a trip.
  # Delivers information about the complete route of a trip. This service can not be called directly but only by reference URLs in a result of a trip or departureBoard request. It contains a list of all stops/stations of this journey including all departure and arrival times (with real-time data if available) and additional information like specific attributes about facilities and other texts.
  # @param ref the ref query parameter, URL decoded, from a URL retrieved as a result of a trip or or departureBoard request
  # @param [Hash] opts the optional parameters
  # @return [JourneyDetail]
  describe 'get_journey_detail test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
