=begin
#Reseplaneraren

#Provides access to Västtrafik journey planner

OpenAPI spec version: 1.10.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.28

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::LocationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LocationApi' do
  before do
    # run before each test
    @instance = SwaggerClient::LocationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LocationApi' do
    it 'should create an instance of LocationApi' do
      expect(@instance).to be_instance_of(SwaggerClient::LocationApi)
    end
  end

  # unit tests for get_all_stops
  # Returns a list of all stops available in the journey planner.
  # Returns a list of all stops available in the journey planner. Be aware that a call of this service is very time consuming and should be only requested when it is really needed.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :format the required response format
  # @option opts [String] :jsonp_callback If JSONP response format is needed, you can append an additional parameter to specify the name of a callback function, and the JSON object will be wrapped by a function call with this name.
  # @return [LocationList]
  describe 'get_all_stops test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_location_by_name
  # Returns a list of possible matches in the journey planner database
  # Performs a pattern matching of a user input to retrieve a list of possible matches in the journey planner database. Possible matches might be stops/stations, points of interest and addresses.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :input a string with the user input
  # @option opts [String] :format the required response format
  # @option opts [String] :jsonp_callback If JSONP response format is needed, you can append an additional parameter to specify the name of a callback function, and the JSON object will be wrapped by a function call with this name.
  # @return [LocationList]
  describe 'get_location_by_name test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_nearby_address
  # Returns the address nearest a given coordinate.
  # 
  # @param origin_coord_lat latitude of coordinate in the WGS84 system
  # @param origin_coord_long longitude of coordinate in the WGS84 system
  # @param [Hash] opts the optional parameters
  # @option opts [String] :format the required response format
  # @option opts [String] :jsonp_callback If JSONP response format is needed, you can append an additional parameter to specify the name of a callback function, and the JSON object will be wrapped by a function call with this name.
  # @return [LocationList]
  describe 'get_nearby_address test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_nearby_stops
  # Returns a list of stops around a given center coordinate.
  # Returns a list of stops around a given center coordinate. The returned results are ordered by their distance to the center coordinate.
  # @param origin_coord_lat latitude of center coordinate in the WGS84 system
  # @param origin_coord_long longitude of center coordinate in the WGS84 system
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :max_no maximum number of returned stops
  # @option opts [Integer] :max_dist maximum distance from the center coordinate
  # @option opts [String] :format the required response format
  # @option opts [String] :jsonp_callback If JSONP response format is needed, you can append an additional parameter to specify the name of a callback function, and the JSON object will be wrapped by a function call with this name.
  # @return [LocationList]
  describe 'get_nearby_stops test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
