=begin
#Reseplaneraren

#Provides access to Västtrafik journey planner

OpenAPI spec version: 1.10.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.28

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SysteminfoApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SysteminfoApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SysteminfoApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SysteminfoApi' do
    it 'should create an instance of SysteminfoApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SysteminfoApi)
    end
  end

  # unit tests for get_system_info
  # Provides information about the journey planner and the underlying data
  # Provides information about the journey planner and underlying data. It will return the begin of end of the timetable period and the creation date of the timetable data.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :format the required response format
  # @option opts [String] :jsonp_callback If JSONP response format is needed, you can append an additional parameter to specify the name of a callback function, and the JSON object will be wrapped by a function call with this name.
  # @return [SystemInfo]
  describe 'get_system_info test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
