=begin
#Reseplaneraren

#Provides access to Västtrafik journey planner

OpenAPI spec version: 1.10.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.28

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/arrival'
require 'swagger_client/models/arrival_board'
require 'swagger_client/models/color'
require 'swagger_client/models/coord_location'
require 'swagger_client/models/creation_date'
require 'swagger_client/models/date_begin'
require 'swagger_client/models/date_end'
require 'swagger_client/models/departure'
require 'swagger_client/models/departure_board'
require 'swagger_client/models/destination'
require 'swagger_client/models/direction'
require 'swagger_client/models/geometry'
require 'swagger_client/models/geometry_ref'
require 'swagger_client/models/journey_detail'
require 'swagger_client/models/journey_detail_ref'
require 'swagger_client/models/journey_id'
require 'swagger_client/models/journey_name'
require 'swagger_client/models/journey_type'
require 'swagger_client/models/leg'
require 'swagger_client/models/live_map'
require 'swagger_client/models/location_list'
require 'swagger_client/models/note'
require 'swagger_client/models/notes'
require 'swagger_client/models/origin'
require 'swagger_client/models/point'
require 'swagger_client/models/points'
require 'swagger_client/models/stop'
require 'swagger_client/models/stop_location'
require 'swagger_client/models/system_info'
require 'swagger_client/models/time_table_data'
require 'swagger_client/models/time_table_period'
require 'swagger_client/models/timetable_info'
require 'swagger_client/models/trip'
require 'swagger_client/models/trip_list'
require 'swagger_client/models/vehicle'

# APIs
require 'swagger_client/api/arrival_board_api'
require 'swagger_client/api/departure_board_api'
require 'swagger_client/api/geometry_api'
require 'swagger_client/api/journey_detail_api'
require 'swagger_client/api/livemap_api'
require 'swagger_client/api/location_api'
require 'swagger_client/api/systeminfo_api'
require 'swagger_client/api/trip_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
