=begin
#Reseplaneraren

#Provides access to Västtrafik journey planner

OpenAPI spec version: 1.10.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.28

=end

require 'uri'

module SwaggerClient
  class JourneyDetailApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Returns information about the complete route of a trip.
    # Delivers information about the complete route of a trip. This service can not be called directly but only by reference URLs in a result of a trip or departureBoard request. It contains a list of all stops/stations of this journey including all departure and arrival times (with real-time data if available) and additional information like specific attributes about facilities and other texts.
    # @param ref the ref query parameter, URL decoded, from a URL retrieved as a result of a trip or or departureBoard request
    # @param [Hash] opts the optional parameters
    # @return [JourneyDetail]
    def get_journey_detail(ref, opts = {})
      data, _status_code, _headers = get_journey_detail_with_http_info(ref, opts)
      data
    end

    # Returns information about the complete route of a trip.
    # Delivers information about the complete route of a trip. This service can not be called directly but only by reference URLs in a result of a trip or departureBoard request. It contains a list of all stops/stations of this journey including all departure and arrival times (with real-time data if available) and additional information like specific attributes about facilities and other texts.
    # @param ref the ref query parameter, URL decoded, from a URL retrieved as a result of a trip or or departureBoard request
    # @param [Hash] opts the optional parameters
    # @return [Array<(JourneyDetail, Fixnum, Hash)>] JourneyDetail data, response status code and response headers
    def get_journey_detail_with_http_info(ref, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: JourneyDetailApi.get_journey_detail ...'
      end
      # verify the required parameter 'ref' is set
      if @api_client.config.client_side_validation && ref.nil?
        fail ArgumentError, "Missing the required parameter 'ref' when calling JourneyDetailApi.get_journey_detail"
      end
      # resource path
      local_var_path = '/journeyDetail'

      # query parameters
      query_params = {}
      query_params[:'ref'] = ref

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/xml', 'application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'JourneyDetail')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: JourneyDetailApi#get_journey_detail\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
